import { useState } from "react";
import { StyleSheet, Text, TextInput, View, Pressable } from "react-native";
import type { MetadataToken } from "@art-pollinator/core";

import { useServices } from "../composition/capabilities-context";

/**
 * AuthoringScreen — issue #55's metadata authoring UX: "a user adds a piece
 * end to end and it swaps successfully." Deliberately unstyled beyond basic
 * layout, matching `library-screen.tsx`/`swap-screen.tsx`'s own convention
 * (real visual design is future work; this batch's scope is proving the
 * wiring, per those screens' own doc comments).
 *
 * ## Design: this screen is "artist publishing" — the same `IngestionService`
 * a venue's own seeding tooling would call
 *
 * Issue #53's `IngestionService` (`@art-pollinator/app`) deliberately does
 * not distinguish "venue seeding" from "artist publishing" at the domain
 * level — see that service's own doc comment. This screen is the *artist
 * publishing* framing of that one operation: a user filling in their own
 * piece's details and adding it to their own device's library. A venue's
 * bulk-seeding tooling (out of scope here — no such UI exists yet) would
 * call the exact same `ingestionService.ingest(...)`, just from a different
 * screen/CLI, with no new service method needed.
 *
 * ## Design: no rights/consent gate in this screen
 *
 * This screen does not ask the user to agree to anything about how their
 * piece will circulate — that gate is explicitly **not built** in this
 * batch, because the thing it would gate on (a real, non-draft consent
 * model, issue #54) does not exist yet. See
 * `docs/rights/consent-model-DRAFT.md` §7 ("no composition root in this
 * codebase should be wired to accept real, non-placeholder, non-test artist
 * content by default as a result of this batch") and this batch's PR
 * description. This screen is exercised in this batch only with synthetic
 * demo content (see below) — wiring a real terms-of-use step in front of it
 * is future work, gated on a real decision this batch does not make.
 *
 * ## Design: a generated synthetic blob, not a real file picker
 *
 * Issue #55 asks for "either picks a local file... or, if picking a real
 * file from the device filesystem is impractical in this sandboxed
 * Expo/RN environment, generates a small synthetic placeholder blob for the
 * demo — document which you did and why." **This screen generates a
 * synthetic blob.** A real file picker (`expo-image-picker` /
 * `expo-document-picker`) needs a real device/simulator with a real
 * filesystem and a real permissions prompt to exercise meaningfully; this
 * sandbox has neither (no iOS/Android device or simulator — the same
 * constraint `composition-root.native.ts`'s own doc comment already
 * discloses for BLE: "none of this... has been run against real
 * hardware"). Wiring a real picker library here would add an untestable,
 * unverified dependency for no benefit over what this batch can actually
 * prove. The generated bytes are UTF-8 text embedding the piece's own title
 * and the current time (so two authored pieces never accidentally collide
 * on content hash) — small, deterministic-shaped, and enough to exercise
 * the real `hashContent` -> `BlobStorePort.put` -> `Library.addItem` path
 * end to end (see `app/src/ingestion/ingestion-to-swap.test.ts` for that
 * same path proven against a real two-device swap). Swapping in a real file
 * picker later is a UI-layer change only — `IngestionService.ingest` already
 * accepts arbitrary blob bytes from any source.
 */
export function AuthoringScreen() {
  const { ingestionService, libraryService } = useServices();

  const [title, setTitle] = useState("");
  const [creator, setCreator] = useState("");
  const [description, setDescription] = useState("");
  const [contentType, setContentType] = useState("text/plain");
  const [status, setStatus] = useState<
    | { readonly kind: "idle" }
    | { readonly kind: "error"; readonly message: string }
    | { readonly kind: "success"; readonly token: MetadataToken }
  >({ kind: "idle" });

  function generateSyntheticBlob(pieceTitle: string): Uint8Array {
    // See this file's doc comment ("a generated synthetic blob, not a real
    // file picker") for why this exists instead of a device file picker.
    const text = `ArtPollinator authored piece: ${pieceTitle} — generated ${new Date().toISOString()}`;
    return new TextEncoder().encode(text);
  }

  async function handleSubmit() {
    if (!title.trim() || !creator.trim()) {
      setStatus({ kind: "error", message: "Title and creator are required." });
      return;
    }

    const blob = generateSyntheticBlob(title.trim());
    const result = await ingestionService.ingest({
      title: title.trim(),
      creator: creator.trim(),
      description: description.trim(),
      contentType,
      blob,
    });

    if (!result.ok) {
      setStatus({ kind: "error", message: result.error });
      return;
    }

    setStatus({ kind: "success", token: result.token });
    setTitle("");
    setCreator("");
    setDescription("");
  }

  const library = libraryService.getLibrary();

  return (
    <View style={styles.container} testID="authoring-screen">
      <Text style={styles.heading}>Add your own piece</Text>
      <Text style={styles.body}>
        Fill this in as an artist publishing your own work — same underlying operation a venue's
        seeding tooling uses (issue #53).
      </Text>

      <TextInput
        style={styles.input}
        placeholder="Title"
        value={title}
        onChangeText={setTitle}
        testID="authoring-title-input"
      />
      <TextInput
        style={styles.input}
        placeholder="Creator (your name or handle)"
        value={creator}
        onChangeText={setCreator}
        testID="authoring-creator-input"
      />
      <TextInput
        style={styles.input}
        placeholder="Description"
        value={description}
        onChangeText={setDescription}
        testID="authoring-description-input"
        multiline
      />
      <TextInput
        style={styles.input}
        placeholder="Content type (e.g. image/jpeg, text/plain)"
        value={contentType}
        onChangeText={setContentType}
        testID="authoring-content-type-input"
      />

      <Text style={styles.body}>
        No file picker in this build — a small synthetic demo blob is generated instead. See this
        screen's own doc comment for why.
      </Text>

      <Pressable onPress={() => void handleSubmit()} testID="authoring-submit-button">
        <Text style={styles.action}>Add to my library</Text>
      </Pressable>

      {status.kind === "error" ? (
        <Text style={styles.error} testID="authoring-error">
          {status.message}
        </Text>
      ) : null}
      {status.kind === "success" ? (
        <Text style={styles.success} testID="authoring-success">
          Added "{status.token.title}" (content hash {status.token.contentHash.slice(0, 12)}…). It
          is now swappable — {library.entries.size} / 10 slots in use.
        </Text>
      ) : null}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    gap: 12,
  },
  heading: {
    fontSize: 20,
    fontWeight: "600",
  },
  body: {
    fontSize: 14,
  },
  input: {
    borderWidth: 1,
    borderColor: "#999",
    borderRadius: 4,
    padding: 8,
    fontSize: 14,
  },
  action: {
    fontSize: 14,
    fontWeight: "600",
    textDecorationLine: "underline",
  },
  error: {
    fontSize: 14,
    color: "red",
  },
  success: {
    fontSize: 14,
    color: "green",
  },
});
